// import { Geist, Geist_Mono } from "next/font/google";
// import './globals.css'
// import ModalManager from "@/components/layouts/Modal/ModalManager";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className="dark">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased `}
//       >
//         {children}
//         <ModalManager /> 
//       </body>
//     </html>
//   );
// }

import { Inter } from "next/font/google";
import './globals.css'
import ModalManager from "@/components/layouts/Modal/ModalManager";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: "NexFile - File Management System",
  description: "Modern file management and collaboration platform",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} antialiased font-sans`}>
        {children}
        <ModalManager /> 
      </body>
    </html>
  );
}